const data = {
    products: [
        {
            name: 'Air Jordan 6 Carmine (2021)',
            image: '/images/p1.jpg',
            brand: 'Air Jordan',
            model: '6',
            colorway: 'Carmine',
            size: '10',
            price: 400,
            category: 'Shoes',
            description: 'Carmine 6...horrible midsole',
            gender: 'Mens',
            releaseDate: new Date(2021, 2, 13, 0, 0, 0, 0),
            isFeatured: false,
            isBestSeller: false,
            isSold: false,
            // dateSold: ,
            quality: 'Deadstock',
            onSale: false,
        },
        {
            name: 'Air Jordan 1 Bred (2016)',
            image: '/images/p1.jpg',
            brand: 'Air Jordan',
            model: '1',
            colorway: 'Bred',
            size: '10.5',
            price: 1000,
            category: 'Shoes',
            description: 'Bred 1...OG',
            gender: 'Mens',
            releaseDate: new Date(2016, 9, 3, 0, 0, 0, 0),
            isFeatured: false,
            isBestSeller: false,
            isSold: false,
            // dateSold: ,
            quality: 'Deadstock',
            onSale: false,
        },
        {
            name: 'Supreme Cross Box Logo Hoodie Olive',
            image: '/images/p1.jpg',
            brand: 'Supreme',
            model: 'Hoodie',
            colorway: 'Olive',
            size: 'L',
            price: 525,
            category: 'Clothing',
            description: 'Supreme F/W 20',
            gender: 'Mens',
            releaseDate: new Date(2020, 12, 3, 0, 0, 0, 0),
            isFeatured: false,
            isBestSeller: true,
            isSold: false,
            // dateSold: ,
            quality: 'Deadstock',
            onSale: false,
        },
        {
            name: 'Travis Scott Playstation Hoodie Black',
            image: '/images/p1.jpg',
            brand: 'Travis Scott',
            model: 'Hoodie',
            colorway: 'Black',
            size: 'M',
            price: 200,
            category: 'Clothing',
            description: 'Playstation release exclusive',
            gender: 'Mens',
            releaseDate: new Date(2019, 11, 10, 0, 0, 0, 0),
            isFeatured: true,
            isBestSeller: true,
            isSold: false,
            // dateSold: ,
            quality: 'Deadstock',
            onSale: false,
        },
        {
            name: 'Jordan 1 Co Japan Neutral Grey (2020)',
            image: '/images/p1.jpg',
            brand: 'Air Jordan',
            model: '1',
            colorway: 'Neutral Grey',
            size: '10',
            price: 330,
            category: 'Shoes',
            description: 'Japanese and shiny',
            gender: 'Mens',
            releaseDate: new Date(2019, 8, 7, 0, 0, 0, 0),
            isFeatured: true,
            isBestSeller: false,
            isSold: false,
            // dateSold: ,
            quality: 'Deadstock',
            onSale: false,
        },
        {
            name: 'Jordan 1 Tokyo Biohack (2020)',
            image: '/images/p1.jpg',
            brand: 'Air Jordan',
            model: '1',
            colorway: 'Biohack',
            size: '12.5',
            price: 375,
            category: 'Shoes',
            description: 'Funky colors',
            gender: 'Mens',
            releaseDate: new Date(2019, 9, 4, 0, 0, 0, 0),
            isFeatured: true,
            isBestSeller: true,
            isSold: true,
            // dateSold: ,
            quality: '9/10',
            onSale: true,
        },
    ]
}

export default data